program Simples;

uses
  Vcl.Forms,
  Menu in 'Formulario\Base\Menu.pas' {FMenu},
  Base in 'Formulario\Base\Base.pas' {FBase},
  Vcl.Themes,
  Vcl.Styles,
  Modelo in 'Formulario\Base\Modelo.pas' {FModelo},
  Cliente in 'Formulario\Cadastros\Cliente.pas' {FCliente},
  ModeloStore in 'Formulario\Base\ModeloStore.pas' {FModeloStore},
  ClienteStore in 'Formulario\Cadastros\ClienteStore.pas' {FClienteStore},
  OS in 'Formulario\Financeiro\OS.pas' {FOS},
  OSStore in 'Formulario\Financeiro\OSStore.pas' {FOSStore},
  Atributos in 'Framework\Atributos.pas',
  Bibli in 'Framework\Bibli.pas',
  Biblioteca in 'Framework\Biblioteca.pas',
  Constantes in 'Framework\Constantes.pas',
  iTECORM in 'Framework\iTECORM.pas',
  uConexaoBD in 'Framework\uConexaoBD.pas',
  VO in 'Framework\VO.pas',
  BasicRepository in 'Repository\BasicRepository.pas',
  BasicService in 'Service\BasicService.pas',
  FnOsVO in 'Vo\FnOsVO.pas',
  OSRepository in 'Repository\OSRepository.pas',
  OSService in 'Service\OSService.pas',
  PsPessoaVO in 'Vo\PsPessoaVO.pas',
  PessoaRepository in 'Repository\PessoaRepository.pas',
  PessoaService in 'Service\PessoaService.pas',
  PsFisicaVO in 'Vo\PsFisicaVO.pas',
  PessoaFisicaRepository in 'Repository\PessoaFisicaRepository.pas',
  PessoaFisicaService in 'Service\PessoaFisicaService.pas',
  PsJuridicaVO in 'Vo\PsJuridicaVO.pas',
  PessoaJuridicaRepository in 'Repository\PessoaJuridicaRepository.pas',
  PessoaJuridicaService in 'Service\PessoaJuridicaService.pas',
  Mensagem in 'Formulario\Base\Mensagem.pas' {FMensagem},
  PsContatoVO in 'Vo\PsContatoVO.pas',
  PessoaContatoRepository in 'Repository\PessoaContatoRepository.pas',
  PessoaContatoService in 'Service\PessoaContatoService.pas',
  CategoriaProduto in 'Formulario\Cadastros\CategoriaProduto.pas' {FCategoriaProduto},
  PrCategoriaVO in 'Vo\PrCategoriaVO.pas',
  CategoriaProdutoRepository in 'Repository\CategoriaProdutoRepository.pas',
  CategoriaProdutoService in 'Service\CategoriaProdutoService.pas',
  CategoriaProdutoStore in 'Formulario\Cadastros\CategoriaProdutoStore.pas' {FCategoriaProdutoStore},
  FnCentroCustoVO in 'Vo\FnCentroCustoVO.pas',
  CentroCustoRepository in 'Repository\CentroCustoRepository.pas',
  CentroCustoService in 'Service\CentroCustoService.pas',
  CentroCusto in 'Formulario\Cadastros\CentroCusto.pas' {FCentroCusto},
  CentroCustoStore in 'Formulario\Cadastros\CentroCustoStore.pas' {FCentroCustoStore},
  PrProdutoVO in 'Vo\PrProdutoVO.pas',
  ProdutoRepository in 'Repository\ProdutoRepository.pas',
  ProdutoService in 'Service\ProdutoService.pas',
  Produto in 'Formulario\Cadastros\Produto.pas' {FProduto},
  ProdutoStore in 'Formulario\Cadastros\ProdutoStore.pas' {FProdutoStore},
  PrTributacaoVO in 'Vo\PrTributacaoVO.pas',
  ProdutoTributacaoRepository in 'Repository\ProdutoTributacaoRepository.pas',
  ProdutoTributacaoService in 'Service\ProdutoTributacaoService.pas',
  ProdutoMedidaRepository in 'Repository\ProdutoMedidaRepository.pas',
  PrMedidaVO in 'Vo\PrMedidaVO.pas',
  ProdutoMedidaService in 'Service\ProdutoMedidaService.pas',
  FnCestVO in 'Vo\FnCestVO.pas',
  ProdutoCestRepository in 'Repository\ProdutoCestRepository.pas',
  ProdutoCestService in 'Service\ProdutoCestService.pas',
  FnCfopVO in 'Vo\FnCfopVO.pas',
  ProdutoCfopRepository in 'Repository\ProdutoCfopRepository.pas',
  ProdutoCfopService in 'Service\ProdutoCfopService.pas',
  UnidadeMedida in 'Formulario\Cadastros\UnidadeMedida.pas' {FUnidadeMedida},
  NCM_CEST in 'Formulario\Cadastros\NCM_CEST.pas' {FNCM_CEST},
  Servico in 'Formulario\Cadastros\Servico.pas' {FServico},
  ServicoStore in 'Formulario\Cadastros\ServicoStore.pas' {FServicoStore},
  PrFornecedorVO in 'Vo\PrFornecedorVO.pas',
  ProdutoFornecedorRepository in 'Repository\ProdutoFornecedorRepository.pas',
  ProdutoFornecedorService in 'Service\ProdutoFornecedorService.pas',
  PsUsuarioVO in 'Vo\PsUsuarioVO.pas',
  PessoaUsuarioRepository in 'Repository\PessoaUsuarioRepository.pas',
  PessoaUsuarioService in 'Service\PessoaUsuarioService.pas',
  Usuario in 'Formulario\Cadastros\Usuario.pas' {FUsuario},
  UsuarioStore in 'Formulario\Cadastros\UsuarioStore.pas' {FUsuarioStore},
  Login in 'Formulario\Base\Login.pas' {FLogin},
  Estoque in 'Formulario\Financeiro\Estoque.pas' {FEstoque},
  PrEstoqueVO in 'Vo\PrEstoqueVO.pas',
  EstoqueRepository in 'Repository\EstoqueRepository.pas',
  EstoqueService in 'Service\EstoqueService.pas',
  InventarioEstoque in 'Formulario\Financeiro\InventarioEstoque.pas' {FInventarioEstoque},
  ViewInventarioEstoqueVO in 'Vo\ViewInventarioEstoqueVO.pas',
  Fornecedor in 'Formulario\Cadastros\Fornecedor.pas' {FFornecedor},
  FornecedorStore in 'Formulario\Cadastros\FornecedorStore.pas' {FFornecedorStore},
  Transportadora in 'Formulario\Cadastros\Transportadora.pas' {FTransportadora},
  TransportadoraStore in 'Formulario\Cadastros\TransportadoraStore.pas' {FTransportadoraStore},
  CompraStore in 'Formulario\Financeiro\CompraStore.pas' {FCompraStore},
  Compra in 'Formulario\Financeiro\Compra.pas' {FCompra},
  CompraRepository in 'Repository\CompraRepository.pas',
  CpCompraVO in 'Vo\CpCompraVO.pas',
  CompraService in 'Service\CompraService.pas',
  CpItemVO in 'Vo\CpItemVO.pas',
  CompraItemRepository in 'Repository\CompraItemRepository.pas',
  CompraItemService in 'Service\CompraItemService.pas',
  ItemStore in 'Formulario\Financeiro\ItemStore.pas' {FItemStore},
  PlanoContaRepository in 'Repository\PlanoContaRepository.pas',
  FnPlanoContaVO in 'Vo\FnPlanoContaVO.pas',
  PlanoContaService in 'Service\PlanoContaService.pas',
  PlanoConta in 'Formulario\Financeiro\PlanoConta.pas' {FPlanoConta},
  PlanoContaStore in 'Formulario\Financeiro\PlanoContaStore.pas' {FPlanoContaStore},
  ParcelaPagar in 'Formulario\Financeiro\ParcelaPagar.pas' {FParcelaPagar},
  CrediarioRepository in 'Repository\CrediarioRepository.pas',
  FnCrediarioVO in 'Vo\FnCrediarioVO.pas',
  CrediarioService in 'Service\CrediarioService.pas',
  Pagamento in 'Formulario\Financeiro\Pagamento.pas' {FPagamento},
  BancoRepository in 'Repository\BancoRepository.pas',
  FnBancoVO in 'Vo\FnBancoVO.pas',
  BancoService in 'Service\BancoService.pas',
  ConfigBoletoRepository in 'Repository\ConfigBoletoRepository.pas',
  FnBancoBoletoVO in 'Vo\FnBancoBoletoVO.pas',
  ConfigBoletoService in 'Service\ConfigBoletoService.pas',
  Banco in 'Formulario\Financeiro\Banco.pas' {FBanco},
  BancoStore in 'Formulario\Financeiro\BancoStore.pas' {FBancoStore},
  VendaRepository in 'Repository\VendaRepository.pas',
  VdVendaVO in 'Vo\VdVendaVO.pas',
  VendaService in 'Service\VendaService.pas',
  Venda in 'Formulario\Financeiro\Venda.pas' {FVenda},
  VendaStore in 'Formulario\Financeiro\VendaStore.pas' {FVendaStore},
  VdItemVO in 'Vo\VdItemVO.pas',
  VendaItemRepository in 'Repository\VendaItemRepository.pas',
  VendaItemService in 'Service\VendaItemService.pas',
  VendaParcelaStore in 'Formulario\Financeiro\VendaParcelaStore.pas' {FVendaParcelasStore},
  VendaEditParcelaStore in 'Formulario\Financeiro\VendaEditParcelaStore.pas' {FVendaEditParcelaStore},
  Sistema in 'Formulario\Base\Sistema.pas' {FSistema},
  DadosEmpresa in 'Formulario\Base\DadosEmpresa.pas' {FDadosEmpresa},
  PsEmpresaVO in 'Vo\PsEmpresaVO.pas',
  DadosEmpresaRepository in 'Repository\DadosEmpresaRepository.pas',
  DadosEmpresaService in 'Service\DadosEmpresaService.pas',
  MarcaEmpresa in 'Formulario\Base\MarcaEmpresa.pas' {FMarcaEmpresa},
  CadastroEmpresa in 'Formulario\Base\CadastroEmpresa.pas' {FCadastroEmpresa},
  ThreadEnviarVendaEmail in 'Framework\ThreadEnviarVendaEmail.pas',
  ThreadEnviarSimplesEmail in 'Framework\ThreadEnviarSimplesEmail.pas',
  NFEStore in 'Formulario\Financeiro\NFEStore.pas' {FNFEStore};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Sky');
  Application.CreateForm(TFMenu, FMenu);
  Application.Run;
end.
